# Generated by Django 5.0.1 on 2024-08-25 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblexpenses',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='tblexpenses',
            name='currency_id',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='TblExpenses',
        ),
    ]
