# Generated by Django 5.0.1 on 2024-08-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_remove_tblexpenses_currency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblexpenses',
            name='currency_id',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblexpenses',
            name='u_id',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblexpenses',
            name='category_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
