# Generated by Django 5.0.1 on 2024-08-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_tblexpenses_currency_id_tblexpenses_u_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='u_id',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
