# Generated by Django 5.0.1 on 2024-08-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_category_u_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblexpenses',
            name='currency_id',
        ),
    ]
