# Generated by Django 5.0.1 on 2024-08-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_tblincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('u_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
