# Generated by Django 5.0.1 on 2024-08-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('expenses', '0009_source_delete_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tblusers'),
        ),
        migrations.AlterField(
            model_name='source',
            name='u_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.tblusers'),
        ),
    ]
