# Generated by Django 5.0.1 on 2024-08-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblUsers',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_email', models.EmailField(max_length=255, unique=True)),
                ('u_password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
